FROM golang:latest AS dev
RUN useradd -ms /bin/bash vscode
RUN apt-get update && apt-get install -y sudo
RUN echo "vscode ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nopasswd
WORKDIR /workspace
COPY .. .
EXPOSE 8080
